# Generated by Django 4.1.3 on 2022-12-02 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.issue'),
        ),
    ]
