# Generated by Django 4.1.3 on 2022-12-06 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_knowledgebase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Status Name')),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Weight Name')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255, verbose_name='Task')),
                ('allocated_date', models.DateField(verbose_name='Allocated Date')),
                ('deadline', models.DateField(verbose_name='Deadline Date')),
                ('completion_date', models.DateField(verbose_name='Completion Date')),
                ('assigned_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helpdesk.staff')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.priority')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.status')),
                ('weight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.weight')),
            ],
        ),
    ]
