# Generated by Django 4.1.3 on 2022-12-06 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0005_knowledgecategory_alter_status_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='helpdesk.knowledgecategory'),
            preserve_default=False,
        ),
    ]
