# Generated by Django 4.1.3 on 2022-12-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0006_knowledgebase_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='completion_date',
            field=models.DateField(blank=True, verbose_name='Completion Date'),
        ),
    ]
