# Generated by Django 4.1.3 on 2022-12-08 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0007_alter_ticket_completion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='weight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helpdesk.weight'),
        ),
    ]
