# Generated by Django 4.1.3 on 2022-12-14 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpdesk', '0010_alter_userrequest_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Issue'),
        ),
        migrations.AlterField(
            model_name='knowledgecategory',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='priority',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.role'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Status Name'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Weight Name'),
        ),
    ]
