# Generated by Django 4.1.3 on 2022-12-05 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_time', models.TimeField(unique=True, verbose_name='Available Time')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Room Name')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Address')),
                ('images', models.ImageField(upload_to='photos/rooms', verbose_name='Images')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Booking Name')),
                ('booking_date_from', models.DateField(verbose_name='From')),
                ('booking_date_to', models.DateField(verbose_name='To')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Description')),
                ('booking_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('booking_time_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_time_from', to='room_booking.availabletime')),
                ('booking_time_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_time_to', to='room_booking.availabletime')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_booking.room')),
            ],
        ),
    ]
