# Generated by Django 4.1.5 on 2023-02-13 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Room Name')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Address')),
                ('images', models.ImageField(upload_to='photos/rooms', verbose_name='Images')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('name', models.CharField(max_length=120, verbose_name='Booking Name')),
                ('from_date', models.DateField(verbose_name='From Date')),
                ('to_date', models.DateField(verbose_name='To Date')),
                ('from_time', models.TimeField(verbose_name='From Time')),
                ('to_time', models.TimeField(verbose_name='To Time')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('booking_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='room_booking.room')),
            ],
        ),
    ]
