# Generated by Django 4.1.5 on 2023-02-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='active_booking',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
