# Generated by Django 4.1.5 on 2023-02-13 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('leave_type', models.CharField(max_length=120, unique=True, verbose_name='Leave Type')),
                ('detail', models.TextField(blank=True, max_length=255, verbose_name='Detail')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('detail', models.TextField(blank=True, max_length=255, verbose_name='Detail')),
                ('from_date', models.DateField(verbose_name='From')),
                ('to_date', models.DateField(verbose_name='To')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('pending_manager_approval', models.BooleanField(default=True, verbose_name='Pending Manager Approval')),
                ('pending_hr_approval', models.BooleanField(default=True, verbose_name='Pending HR Approval')),
                ('manager_approved', models.BooleanField(default=False, verbose_name='Manager Approved')),
                ('hr_approved', models.BooleanField(default=False, verbose_name='HR Approved')),
                ('manager_comment', models.TextField(blank=True, max_length=255, verbose_name='Manager Comment')),
                ('hr_comment', models.TextField(blank=True, max_length=255, verbose_name='HR Comment')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_request_system.leavetype')),
                ('requester_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
