# Generated by Django 4.1.5 on 2023-02-13 10:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=50)),
                ('manager', models.EmailField(blank=True, max_length=100)),
                ('hr', models.EmailField(blank=True, max_length=100)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superadmin', models.BooleanField(default=False)),
                ('allow_booking', models.BooleanField(default=False)),
                ('allow_leaverequest', models.BooleanField(default=False)),
                ('allow_helpdesk', models.BooleanField(default=False)),
                ('is_booking_admin', models.BooleanField(default=False)),
                ('is_booking_superadmin', models.BooleanField(default=False)),
                ('is_leaverequest_admin', models.BooleanField(default=False)),
                ('is_leaverequest_superadmin', models.BooleanField(default=False)),
                ('is_helpdesk_admin', models.BooleanField(default=False)),
                ('is_helpdesk_superadmin', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
