# Generated by Django 4.1.3 on 2022-12-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='hr',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='manager',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
