# Generated by Django 4.1.3 on 2022-12-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_hr_account_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_booking_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_booking_superadmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_helpdesk_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_helpdesk_superadmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_leaverequest_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_leaverequest_superadmin',
            field=models.BooleanField(default=False),
        ),
    ]
