# Generated by Django 4.1.3 on 2022-12-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_is_booking_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='allow_booking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='allow_helpdesk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='allow_leaverequest',
            field=models.BooleanField(default=False),
        ),
    ]
